language: python
python:
    - "3.6"
before_install:
	- sudo apt-get -y install capnproto
install:
    - pip install -r requirements.txt
    - pip install -e .
script:
    - mypy
    - flake8
    - cd tests && make
